name: Pobieraj mecze codziennie

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod z repozytorium
        uses: actions/checkout@v4

      - name: Zainstaluj Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Zainstaluj biblioteki
        run: pip install requests supabase

      - name: Uruchom skrypt
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python pobierz_mecze.py
